export const UserMapper = (user) => {
    const {
      name,
      email,
      phone,
      state,
      userType,
      country,
      hasPackage,
      packagePurchasedDate,
      packageExpireDate,
      packageDetails,
      allowNotifications,
      externalUserId,
      token,
      profileImage,
      about,
      gender,
      isActive,
      categories,
      isVerified
    } = user;
    return {
      name,
      email,
      phone,
      state,
      userType,
      country,
      hasPackage,
      packagePurchasedDate,
      packageExpireDate,
      packageDetails,
      allowNotifications,
      externalUserId,
      token,
      profileImage,
      about,
      gender,
      isActive,
      categories,
      isVerified
    };
  };
  
  export const LoginUserMapper = (user, token) => {
    const {
      _id,
      name,
      email,
      phone,
      state,
      userType,
      country,
      profileImage,
      hasPackage,
      packagePurchasedDate,
      packageExpireDate,
      packageDetails,
      about,
      gender,
      isActive,
      isVerified,
      allowNotifications,
      externalUserId,
      categories,
    } = user;
    return {
      _id,
      name,
      email,
      phone,
      state,
      userType,
      token,
      country,
      profileImage,
      hasPackage,
      packagePurchasedDate,
      packageExpireDate,
      packageDetails,
      about,
      gender,
      isActive,
      isVerified,
      allowNotifications,
      externalUserId,
      categories,
    };
  };
  